# Generated by Django 6.0.5 on 2026-05-15 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plan', models.CharField(max_length=100)),
                ('prix_plan', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_debut', models.DateField(auto_now_add=True)),
                ('date_d_expiration', models.DateField()),
                ('est_active', models.BooleanField(default=True)),
                ('boutique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='shops.boutique')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='subscribes.plan')),
            ],
        ),
    ]
