# Generated by Django 6.0.5 on 2026-05-15 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_fournisseur', models.CharField(max_length=255)),
                ('nom_fournisseur', models.CharField(max_length=255)),
                ('adresse_fournisseur', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_fournisseur', models.CharField(blank=True, max_length=20, null=True)),
                ('date_enregistrement_fournisseur', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=255)),
                ('stock_quantite', models.IntegerField(default=0)),
                ('prix_d_achat', models.FloatField()),
                ('prix_de_vente', models.FloatField()),
                ('benefice_sur_vente', models.FloatField(editable=False)),
                ('date_stockage', models.DateField(auto_now_add=True)),
                ('alert_stock', models.IntegerField(default=5)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.boutique')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée Stock'), ('VENTE', 'Vente'), ('PERTE', 'Perte/Avarie'), ('RETOUR', 'Retour Client')], max_length=20)),
                ('quantite', models.PositiveIntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('nouveau_prix_achat', models.FloatField(blank=True, help_text="Saisir si le prix d'achat a changé", null=True)),
                ('nouveau_prix_vente', models.FloatField(blank=True, help_text='Saisir si le prix de vente a changé', null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='products.produit')),
            ],
        ),
    ]
