# Generated by Django 6.0.5 on 2026-05-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='nouveau_benefice_sur_vente',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
