# Generated by Django 6.0.5 on 2026-05-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_mouvementstock_nouveau_benefice_sur_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='nouveau_prix_achat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='nouveau_prix_vente',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
