# Generated by Django 6.0.5 on 2026-06-02 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_mouvementstock_nouveau_prix_achat_and_more'),
        ('shops', '0003_alter_boutique_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='shops.boutique'),
        ),
    ]
