export const styles = {
  pageWrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    backgroundColor: '#f5f6fa',
    fontFamily: "'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    padding: '20px',
  },
  loginCard: {
    width: '100%',
    maxWidth: '420px',
    backgroundColor: '#ffffff',
    padding: '40px 30px',
    borderRadius: '12px',
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.05)',
    border: '1px solid #e1e8ed',
  },
  brandTitle: {
    textAlign: 'center',
    color: '#2c3e50',
    fontSize: '28px',
    fontWeight: 'bold',
    margin: '0 0 5px 0',
    letterSpacing: '0.5px',
  },
  brandSubtitle: {
    textAlign: 'center',
    color: '#95a5a6',
    fontSize: '13px',
    margin: '0 0 35px 0',
  },
  formTitle: {
    color: '#34495e',
    fontSize: '18px',
    fontWeight: '600',
    marginBottom: '20px',
  },
  errorAlert: {
    padding: '12px 15px',
    backgroundColor: '#fdf2f2',
    color: '#de3b3b',
    borderRadius: '6px',
    border: '1px solid #fbc4c4',
    marginBottom: '20px',
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
  },
  inputGroup: {
    marginBottom: '20px',
    display: 'flex',
    flexDirection: 'column',
  },
  label: {
    color: '#7f8c8d',
    fontSize: '13px',
    fontWeight: '500',
    marginBottom: '6px',
  },
  input: {
    padding: '12px',
    borderRadius: '6px',
    border: '1px solid #cccccc',
    fontSize: '15px',
    color: '#2c3e50',
    outline: 'none',
    transition: 'border-color 0.2s ease',
    ':focus': {
      borderColor: '#3498db',
    }
  },
  submitButton: {
    width: '100%',
    padding: '14px',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '16px',
    fontWeight: 'bold',
    transition: 'background-color 0.2s ease',
    marginTop: '10px',
    boxShadow: '0 4px 12px rgba(52, 152, 219, 0.2)',
  },
  footerText: {
    textAlign: 'center',
    color: '#7f8c8d',
    fontSize: '14px',
    marginTop: '25px',
    marginBottom: '0',
  },
  registerLink: {
    color: '#3498db',
    textDecoration: 'none',
    fontWeight: '600',
    marginLeft: '3px',
  }
};