# Generated by Django 6.0.5 on 2026-05-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=255)),
                ('logo_boutique', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('devise_monetaire', models.CharField(default='XOF', max_length=10)),
                ('pays', models.CharField(default='Sénégal', max_length=100)),
                ('region', models.CharField(choices=[('TAMBA', 'Tambacounda'), ('BAKEL', 'Bakel'), ('DAKAR', 'Dakar')], max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
