# Generated by Django 6.0.5 on 2026-05-15 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='proprietaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mes_boutiques', to=settings.AUTH_USER_MODEL),
        ),
    ]
