# Generated by Django 6.0.5 on 2026-06-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='region',
            field=models.CharField(choices=[('TAMBA', 'Tambacounda'), ('BAKEL', 'Bakel'), ('DAKAR', 'Dakar'), ('ZIG', 'Ziguinchor')], max_length=50),
        ),
    ]
