# Generated by Django 6.0.5 on 2026-05-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_client', models.CharField(max_length=255)),
                ('last_name_client', models.CharField(max_length=255)),
                ('number_call_client', models.BigIntegerField()),
                ('date_compte', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.FloatField()),
                ('montant_paye', models.FloatField(default=0)),
                ('reste_a_payer', models.FloatField()),
                ('type_de_vente', models.CharField(choices=[('COMPTANT', 'Vente au comptant'), ('DETTE', 'Vente à crédit')], max_length=20)),
                ('statut_paiement', models.CharField(choices=[('PAYE', 'Payé'), ('PARTIEL', 'Partiel'), ('ATTENTE', 'En attente')], max_length=20)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_verse', models.FloatField()),
                ('date_de_versement', models.DateTimeField(auto_now_add=True)),
                ('mode_de_paiement', models.CharField(choices=[('ESPECE', 'Espèces'), ('OM', 'Orange Money'), ('WAVE', 'Wave'), ('FREE', 'Free Money')], max_length=20)),
            ],
        ),
    ]
