# Generated by Django 6.0.5 on 2026-05-15 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='boutique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.boutique'),
        ),
        migrations.AddField(
            model_name='vente',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.boutique'),
        ),
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.client'),
        ),
        migrations.AddField(
            model_name='versement',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='sales.vente'),
        ),
    ]
