# Generated by Django 6.0.5 on 2026-05-16 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_mouvementstock_nouveau_prix_achat_and_more'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='description_vente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='montant_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vente',
            name='reste_a_payer',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, help_text="Nom de l'article si absent du catalogue de stock", max_length=255, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.FloatField()),
                ('total', models.FloatField()),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='sales.vente')),
            ],
        ),
    ]
